root = "."
testdata_dir = "examples"
tmp_dir = "tmp"

[build]
  bin = "tmp/main run s -L -w examples/npm --npm 'search:*'"
  cmd = "go build -o ./tmp/main ."
  delay = 100
  exclude_dir = ["tmp", "examples"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
