# schema: https://golangci-lint.run/jsonschema/golangci.jsonschema.json

issues:
  exclude-rules:
    - path: cmd/
      linters:
        - gochecknoglobals
        - gochecknoinits

linters:
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused

  disable:
    - depguard # enforces dependency allow list; not using allow list

    # annoying/bad
    - err113 # disallows returning one-off errors; annoying
    - gofumpt # different code formatter; bad
    - nlreturn # requires blank line before return; annoying
    - varnamelen # limits variable name length; too many false positives
    - wsl # whitespace/cuddle rules; tedious

linters-settings:
  cyclop:
    max-complexity: 30

  exhaustruct:
    exclude:
      - "^github.com/spf13/cobra.Command$"

  funlen:
    lines: 100
    ignore-comments: true

  mnd:
    ignored-functions:
      - strings.SplitN
