version: 2

before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    ldflags:
      - -s -w -X github.com/jclem/konk/cmd.Version={{ .Version }} -X github.com/jclem/konk/cmd.Commit={{ .Commit }} -X github.com/jclem/konk/cmd.BuiltAt={{ .Date }}
brews:
  - repository:
      owner: jclem
      name: homebrew-tap
    directory: Formula
    homepage: https://github.com/jclem/konk
    license: MIT
    test: system "#{bin}/konk --version"
