before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    ldflags:
      - -s -w -X github.com/jclem/konk/cmd.Version={{ .Version }} -X github.com/jclem/konk/cmd.Commit={{ .Commit }} -X github.com/jclem/konk/cmd.BuiltAt={{ .Date }}
archives:
  - replacements:
      darwin: macOS
      linux: Linux
      386: 32-bit
      amd64: 64-bit